name: Build BaseTools for Linux

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential uuid-dev iasl nasm python3-pip

    - name: Build BaseTools
      run: |
        cd BaseTools/Source/C/TianoCompress
        make

    - name: Archive Linux Bin Files
      uses: actions/upload-artifact@v4
      with:
        name: bin-linux
        path: BaseTools/Source/C/bin/
