name: Build BaseTools

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential uuid-dev iasl nasm python3

    - name: Build BaseTools
      run: |
        cd BaseTools
        make

    - name: Archive BaseTools binaries
      uses: actions/upload-artifact@v4
      with:
        name: BaseTools-bin
        path: BaseTools/BinWrappers/PosixLike/ # 或根据实际构建输出路径调整
